name: Docker Image Selection and Deployment

on:
  workflow_dispatch:
    inputs:
      docker_image_choice:
        description: 'Choose a Docker image'
        required: true
        default: 'node'
        options:
          - 'node'
          - 'mysql'
          - 'jenkins'
          - 'nginx'
          - 'openjdk'

jobs:
  build-and-run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Echo chosen Docker image
        run: echo ${{ github.event.inputs.docker_image_choice }}

      - name: Pull and Run Docker container
        run: |
          case "${{ github.event.inputs.docker_image_choice }}" in
            "node") docker pull node:latest && docker run -d node:latest ;;
            "mysql") docker pull mysql:latest && docker run -d mysql:latest ;;
            "jenkins") docker pull jenkins/jenkins:latest && docker run -d jenkins/jenkins:latest ;;
            "nginx") docker pull nginx:latest && docker run -d nginx:latest ;;
            "openjdk") docker pull openjdk:latest && docker run -d openjdk:latest ;;
            *) echo "Invalid Docker image choice" ;;
          esac
