name: Choose and Run Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Select Docker an image out of [pytorch, nginx, jenkins, alpine, mysql]'
        required: true
        default: 'pytorch'
        options: ['pytorch', 'nginx', 'jenkins', 'alpine', 'mysql']

jobs:
  choose_and_run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run Docker Image
      run: |
        case "${{ github.event.inputs.docker_image }}" in
          "pytorch") docker run pytorch ;;
          "nginx") docker run nginx ;;
          "jenkins") docker run jenkins ;;
          "alpine") docker run alpine ;;
          "mysql") docker run mysql ;;
          *) echo "Invalid Docker image selected" ;;
        esac
