name: Choose and Run Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Select Docker image'
        required: true
        default: 'image1'
        options: ['image1', 'image2', 'image3', 'image4', 'image5']

jobs:
  choose_and_run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run Docker Image
      run: |
        docker run ${{ github.event.inputs.docker_image }}
