name: Choose and Run Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Select Docker image'
        required: true
        default: 'pytorch'
        options: [ 'pytorch', 'nginx', 'jenkins', 'alpine', 'mongo' ]

jobs:
  choose_and_run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Pull Docker Image
      run: |
        case "${{ github.event.inputs.docker_image }}" in
          "pytorch") docker pull pytorch ;;
          "nginx") docker pull nginx ;;
          "jenkins") docker pull jenkins ;;
          "alpine") docker pull alpine ;;
          "mongo") docker pull mongo ;;
          *) echo "Invalid Docker image selected" ;;
        esac

    - name: Run Docker Image
      run: |
        case "${{ github.event.inputs.docker_image }}" in
          "pytorch") docker run pytorch ;;
          "nginx") docker run nginx ;;
          "jenkins") docker run jenkins ;;
          "alpine") docker run alpine ;;
          "mongo") docker run mongo ;;
          *) echo "Invalid Docker image selected" ;;
        esac
