name: Choose and Run Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_image_choice:
        description: 'Choose a Docker image from alpine, mongo, jenkins, php, ubuntu'
        required: true
        default: 'alpine'
        options:
          - 'alpine'
          - 'mongo'
          - 'jenkins'
          - 'php'
          - 'ubuntu'

jobs:
  build-and-run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Echo chosen Docker image
        run: echo ${{ github.event.inputs.docker_image_choice }}

      - name: Pull and Run Docker container
        run: |
          case "${{ github.event.inputs.docker_image_choice }}" in
            "alpine") docker pull alpine:latest && docker run -d alpine:latest ;;
            "mongo") docker pull mongo:latest && docker run -d mongo:latest ;;
            "jenkins") docker pull jenkins/jenkins:latest && docker run -d jenkins/jenkins:latest ;;
            "php") docker pull php:latest && docker run -d php:latest ;;
            "ubuntu") docker pull ubuntu:latest && docker run -d ubuntu:latest ;;
            *) echo "Invalid Docker image choice" ;;
          esac
